/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panels;
import customBackend.Observer;
import customBackend.Observable;
import javax.swing.ImageIcon;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
/**
 *
 * @author Erik
 */
public class sideMenuPanel extends javax.swing.JPanel {

    private Observer observer = Observer.getInstance();
    private Observable observable;
    /**
     * Creates new form sideMenuPanel
     */
    public sideMenuPanel() {
        initComponents();
        setIcons();
        
        MenuTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        
    }
    
    public void setIcons(){
        renderer = new DefaultTreeCellRenderer();
        renderer.setLeafIcon(null);
        renderer.setClosedIcon(null);
        renderer.setOpenIcon(null);
        MenuTree.setCellRenderer(renderer);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MenuTree = new javax.swing.JTree();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(304, 265));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        MenuTree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Hem");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Varor");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Kött");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Frukt & Grönt");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Godis");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Dryck");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Recept");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hot dogs");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pizza");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ravioli");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("bananas");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Erbjudande");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Favoritprodukter");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mina inköpslistor");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mina köp");
        treeNode1.add(treeNode2);
        MenuTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        MenuTree.setRootVisible(false);
        MenuTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuTreeMouseClicked(evt);
            }
        });
        MenuTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                MenuTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(MenuTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTreeMouseClicked
    
    }//GEN-LAST:event_MenuTreeMouseClicked

    private void MenuTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_MenuTreeValueChanged
        //Returns the last path element of the selection.
        //This method is useful only when the selection model allows a single selection.
        node = (DefaultMutableTreeNode) MenuTree.getLastSelectedPathComponent();

        if (node == null)
        //Nothing is selected.  
        return;

        Object nodeInfo = node.getUserObject();
        
        if(nodeInfo.toString().equals("Varor") || nodeInfo.toString().equals("Recept")){
            TreePath path = evt.getPath();
            if(MenuTree.isCollapsed(path)){
                openNode(path);
            } else {
                closeNode(path);
            }
        }
        if (node.isLeaf()) {
            //bad coding level 9000
            selectedItem = nodeInfo.toString();
            notifyObserver();
        }
    }//GEN-LAST:event_MenuTreeValueChanged
    
    private void openNode(TreePath path){
        MenuTree.expandPath(path);
    }
    
    /*private void closeNode(TreePath path){
        MenuTree.collapsePath(path);
    }^*/
    
    private void notifyObserver(){
        observable= observer.getObserver();
        observable.update(selectedItem);
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree MenuTree;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private DefaultTreeCellRenderer renderer;
    private String selectedItem;
    private DefaultMutableTreeNode node;
    //Observer observer = new IMatFrame();
}
