/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cards;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import se.chalmers.ait.dat215.project.Order;
import se.chalmers.ait.dat215.project.ShoppingItem;


public class ReceiptCard extends javax.swing.JPanel {

    DefaultTableModel tablemodel;
    
    /**
     * Creates new form ReceiptCard
     */
    public ReceiptCard() {
        initComponents();
    }
    
    
    
    public void loadOrder(Order o) {
        this.dateLabel.setText(o.getDate().getYear() +"-"+ o.getDate().getMonth() +"-"+ o.getDate().getDay());
        this.orderNumberLabel.setText("Ordernummer: " + o.getOrderNumber());
        int tot = this.populateTable(o.getItems());
        this.subtotalLabel.setText("Totalpris: "+tot+" kr");
    }
 
    private int populateTable(List<ShoppingItem> items) {
        tablemodel = new DefaultTableModel(new Object[][] {}, new Object[] {"Vara","Pris/st","Mängd","Totalpris"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        int subtotal=0;
        for (ShoppingItem i : items) {
            tablemodel.addRow(new Object[] {
                i.getProduct().getName(),
                i.getProduct().getPrice() +" "+i.getProduct().getUnit(),
                i.getAmount() + " " + i.getProduct().getUnitSuffix(),
                i.getTotal() + " kr"
            });
            subtotal += i.getTotal();
        }
        this.jTable1.setModel(tablemodel);
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
        
        return subtotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dateLabel = new javax.swing.JLabel();
        orderNumberLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tack för ditt köp!");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        dateLabel.setText("datum");

        orderNumberLabel.setText("Ordernummer: ");

        subtotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subtotalLabel.setText("Totalt:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orderNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateLabel)))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(subtotalLabel)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel)
                    .addComponent(orderNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subtotalLabel)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel orderNumberLabel;
    private javax.swing.JLabel subtotalLabel;
    // End of variables declaration//GEN-END:variables
}
