/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cards;

import customBackend.EventHandler;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import se.chalmers.ait.dat215.project.Order;
import se.chalmers.ait.dat215.project.ShoppingItem;


public class ReceiptCard extends javax.swing.JPanel {

    private DefaultTableModel tablemodel;
    private EventHandler ehandler;
    /**
     * Creates new form ReceiptCard
     */
    public ReceiptCard() {
        initComponents();
        ehandler = EventHandler.getInstance();
    }
    
    
    
    public void loadOrder(Order o) {
        this.orderNumberLabel.setText("Ordernummer: " + o.getOrderNumber());
        int tot = this.populateTable(o.getItems());
        this.subtotalLabel.setText("Totalpris: "+tot+" kr");
    }
 
    private int populateTable(List<ShoppingItem> items) {
        tablemodel = new DefaultTableModel(new Object[][] {}, new Object[] {"Vara","Pris/st","Mängd","Totalpris"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        int subtotal=0;
        for (ShoppingItem i : items) {
            tablemodel.addRow(new Object[] {
                i.getProduct().getName(),
                i.getProduct().getPrice() +" "+i.getProduct().getUnit(),
                i.getAmount() + " " + i.getProduct().getUnitSuffix(),
                i.getTotal() + " kr"
            });
            subtotal += i.getTotal();
        }
        this.jTable1.setModel(tablemodel);
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
        
        return subtotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        orderNumberLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tack för ditt köp!");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        orderNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        orderNumberLabel.setText("Ordernummer: ");

        subtotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subtotalLabel.setText("Totalt:");

        jButton1.setText("Till start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderNumberLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subtotalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(orderNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalLabel)
                    .addComponent(jButton1))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ehandler.getObserver().update("Hem");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel orderNumberLabel;
    private javax.swing.JLabel subtotalLabel;
    // End of variables declaration//GEN-END:variables
}
